### PR TITLE
Add cmake build system redo

### PR DESCRIPTION
**Pull request by tcumby**
Hi Ryan,

So I gave up sorting out rebase conflicts and just created a new branch and copied the files over from another working copy with my  `add-cmake-build-system` branch checked out.

Best regards,
Ty

### CODE REVIEW

**Comment by ryanmaguire** [comment]
Thanks, Ty.

Sorry for the mess, I didn't think changing the author of commits would cause such an issue.
I hope to be able to read through all of this soon and merge your CMake code.

As a heads up, we will be merging rss_ringoccs v1.3-dev to the master branch soon.
I'm not sure if you wrote a CMake build for that library as well.

-Ryan

**Comment by tcumby** [comment]
Hi Ryan,

I cobbled together the start of one on my [rss_ringoccs fork](https://github.com/tcumby/rss_ringoccs/tree/v1.3dev-add-cmake-system-redo). It's a little rough, but it's fetching my fork libtmpl and building it as part of the rss_ringoccs build. I've also reworked [setup.py](https://github.com/tcumby/rss_ringoccs/blob/v1.3dev-add-cmake-system-redo/setup.py) to use scikit-build so that we can use the CMake build system as part of the Python packaging. Likely I still need to ensure that the RUNPATH / @rpath entries are set correctly for Linux and macOS, respectively.

Best regards,
Ty

**Comment by ryanmaguire** [comment]
Hi Ty,

I'd caution you not to worry too much about rss_ringoccs build system just yet.
By the summer the repository will look quite different.
We've experience some more dependency-hell over the past few weeks.
Numpy had some functions deprecated and removed since our 1.2 release.
We'll be transitioning everything to C for the sake of future-proofing this project.
The only dependency will be libtmpl and CSPICE.

If you can find a convenient way of building CSPICE in a portable manner, that would be greatly appreciated.
I was digging through the spiceypy repo myself on how they do this.

Best,
Ryan

**Comment by tcumby** [comment]
Hi Ryan,

Looks like someone has already done so for macOS, Windows and Linux by posting a Conan recipe for its build [link](https://conan.io/center/cspice). Are either of the 0067 or 0066 versions what is needed? I'd just need to switch rss_ringoccs over to Conan and we could just list it as a dependency.

Best regards,
Ty

**Comment by tcumby** [comment]
I think I have the CMake and python build system working (with CSPICE 0067) for rss_ringoccs. I'll inspect it some more tomorrow and likely issue a PR.

**Comment by ryanmaguire** [comment]
Sorry for the delay on this.
Creating a new branch from this PR.
I'll merge that into master when time permits.

**Pull request merged**
