### PR TITLE
Add cmake build system

### PR DESCRIPTION
**Pull request by tcumby**
Hi Ryan,

Apologies in advance for the large PR. 

I've tried to restrict my changes to CMake (and dependent) files, but I went the route of using CMake to generate an export header (using [generate_export_header](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html?highlight=generate_export_header)) so symbols are exported for MSVC. The header it generates is specific to the compiler used, so I can't merely commit it. I may need to rethink this approach and revisit using [WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html?highlight=windows_export_all_symbols) as it will break your build system.

I have build targets defined for the main library as well as all tests and examples. ASM and FASM are working, but I haven't tested out builds with Qemu yet. The dependencies for the tests/examples are integrated using [Conan](https://conan.io/) where possible (see conanfile.txt) and CMake's [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) otherwise.

To try out the build system, I'd install CMake, Conan and Ninja following the instructions in README.md. Then you can execute the build using the presets in place for the Github CI:

```shell
cmake --preset ci-linux
```

```shell
cmake --build --preset ci-linux
```

The details for these presets are in the `CMakePresets.json` file with the build system generated to `../build/libtmpl` and installed to `../install/libtmpl`.

I've tried to set up the build system so it can be easily consumed using other CMake build systems, and potentially we could add libtmpl to Conan's registry for even easier distribution.

Best regards,
Ty

### CODE REVIEW

**Comment by ryanmaguire** [comment]
Hi Ty,

Firstly, thanks for doing this!
My CMake knowledge is next to zero.
A few questions.

1.)
The layout seems to seriously defeat the KISS principle.
There are text files scattered throughout the project, and it
would seem that whenever a file is deleted or added, the
corresponding text file needs to be updated. Is there a way
to consolidate this into a single file, like the Makefile, shell script,
and (very primitive) batch file I have up? And also automate the
updating process? The only time I need to change the Makefile
or shell script is when a new inline function or assembly function
is added, in which case the EXCLUDE variables are appended. If
a regular .c file is added or deleted, the Makefile and shell script
do not need to be changed.

2.)
After following the build instructions, I am met with
    CMake 3.23 or higher is required.  You are running version 3.18.4
I am using the cmake that comes from the Debian stable repository.
It seems 3.23 is relatively new, being released earlier this year.
Are there any particular features from the newer version of CMake
you are using? This would limit portability a bit.

3.)
What is the point of TMPL_EXPORT? I've no idea what could be a
prefix to extern, and it makes the declarations in the headers a
little more verbose and confusing. Is this a CMake thing?

4.)
The only dependencies for the project are for testing purposes,
and it seems these are downloaded / installed. Is this the default?
Linasm, for example, while being a great library, is exclusively an
x86_64 GNU/Linux Library. I'm fairly certain FASM for this library
won't work with it in other environments (x86, or Windows),
and macOS and FreeBSD don't have FASM at all, nor do other
architectures. Trying to install Linasm in the situations would
halt the build process, but Linasm is not actually needed here.


In the coming months more and more of libtmpl will be finalized.
I anticipate having more-or-less finished versions of the following soon:

bytes/
complex/
fft/
integer/
math/
optics/
special_functions/
string/
vec2/
vec3/
void_pointer/
window_functions/

Not-coincidentally, these are the parts of the library rss_ringoccs uses.
special_functions needs a large overhaul. The versions up currently
were just naive first drafts to get things moving.

-Ryan

**Comment by tcumby** [comment]
Hi Ryan,

1. Having the CMakeLists.txt files scattered throughout actually makes the build system specification simpler as you then can reference files by their filename instead of a file path. Also, it allows you to localize the details for different component better. Also, personally I find it easier to understand as it breaks up the build system specification into more coherent "chunks". (I had to make a custom build of [pytorch](https://github.com/pytorch/pytorch) for work a few weeks ago, and it would have made it much more daunting if it was a monolithic CMakeLists.txt file.

Regarding the maintenance issue you brought up, I can try using file glob expressions to construct the file list, but that has portability issues (i.e. not all project file generators can use it safely; [more details here](https://cmake.org/cmake/help/latest/command/file.html#glob)) in CMake. That being said, if it works for Makefile, Ninja build file, VS project file and XCode project file generation, it's probably good enough.

2. I'm using the new [FILE_SET](https://cmake.org/cmake/help/latest/command/target_sources.html#file-sets) specification to more gracefully handle the header files during the install phase of CMake. Also, the CMakePresets.json file syntax started in 3.19, and continues to develop.

CMake is also available as a [package on pypi.org](https://pypi.org/project/cmake/). Kitware, the developers of CMake, keep it reasonably up to date.

3. `TMPL_EXPORT` is primarily for Windows as symbol visibility is hidden by default for Windows. It is set to declspec(dllexport)/declspec(dllimport) by the tmpl_exports.h file I generate using CMake [generate_export_header()](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html?highlight=generate_export_header) function. I can explore forgoing this approach as CMake library targets do have a Windows-only option to force symbol visibility for all symbols (I tried it initially and hit a linker error).

4. I can ensure that testing-only dependencies are only downloaded when the build of tests are requested.

Best regards,
Ty

**Comment by tcumby** [comment]
The header/source list specification by glob expressions is in place (and hopefully in a generator-portable manner).

**Comment by tcumby** [comment]
Hi Ryan,

I have [builds succeeding](https://github.com/tcumby/libtmpl/actions/runs/4337881220/jobs/7574182016) on the Github CI runners (macOS Ventura, Ubuntu 22.04 and Win 11). The tests are running but there is some issue on Windows that I need to sort out.

Best regards,
Ty

**Comment by tcumby** [comment]
Hi Ryan,

After fixing a PATH environment variable issue and the heap corruption bug in one test, all tests are passing on macOS, Windows and Linux x86-64: https://github.com/tcumby/libtmpl/actions/runs/4398849607.

Best regards,
Ty

**Comment by ryanmaguire** [comment]
Closed this by accident while trying to change the git history. Let me see what I can do.

**Comment by ryanmaguire** [comment]
It seems a force push closes all pull requests, and they can't be re-opened.
Can you resubmit the requests?
All of the code is the same, I rewrote the git history to have all my commits under one name and email.

**Pull request closed without merging**
